<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DebugType>embedded</DebugType>
    <TargetName>$(AssemblyName).net</TargetName>
    <Configurations>Release RedM;Release FiveM;Debug RedM;Debug FiveM</Configurations>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug FiveM' Or '$(Configuration)' == 'Release FiveM'">
    <DefineConstants>FIVEM</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug RedM' Or '$(Configuration)' == 'Release RedM'">
    <DefineConstants>REDM</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />

    <ProjectReference Include="..\MenuAPI\MenuAPI.csproj" />

    <!-- currently hardcoded path as no nuget package for RedM exists yet -->
    <Reference Include="CitizenFX.Core.Client" Condition="'$(Configuration)' == 'Release RedM' Or '$(Configuration)' == 'Debug RedM'">
      <HintPath>..\dependencies\RedM\CitizenFX.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.FiveM.Client" Version="0.0.2-alpha" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if &quot;$(ConfigurationName)&quot; == &quot;Release RedM&quot; (&#xD;&#xA;  if exist &quot;$(SolutionDir)postbuild-redm.cmd&quot; (&#xD;&#xA;    &quot;$(SolutionDir)postbuild-redm.cmd&quot;&#xD;&#xA;  )&#xD;&#xA;) else if &quot;$(ConfigurationName)&quot; == &quot;Release FiveM&quot; (&#xD;&#xA;  if exist &quot;$(SolutionDir)\postbuild-fivem.cmd&quot; (&#xD;&#xA;    &quot;$(SolutionDir)\postbuild-fivem.cmd&quot;&#xD;&#xA;  )&#xD;&#xA;)&#xD;&#xA;" />
  </Target>

</Project>