<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DebugType>embedded</DebugType>
    <TargetName>$(AssemblyName).net</TargetName>
    <Configurations>Release FiveM;Debug FiveM</Configurations>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug FiveM' Or '$(Configuration)' == 'Release FiveM'">
    <DefineConstants>FIVEM</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />

    <ProjectReference Include="..\MenuAPI\MenuAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.FiveM.Client" Version="0.0.2-alpha" />
  </ItemGroup>


</Project>
